### ISSUE TITLE
goto instead of do-while(0)

### ISSUE THREAD

**Issue by ShaharAriel** [meni181818/debt_management#1]
To my opinion the `goto` is better and is a cleaner code in your example: look at here:
https://stackoverflow.com/questions/18507518/what-are-some-better-ways-to-avoid-the-do-while0-hack-in-c

https://github.com/meni181818/debt_management/blob/75a27ed9ed3f82121d0273271dc4fdadfa054d8a/main.c#L19

**Comment by meni181818** [comment]
are you sure? because it's commonly said that it is better to avoid using `goto`..?
i actually chose this as a replacement for goto.

**Comment by meni181818** [comment]
changed in main.c and in data_structure_build.c

**Comment by ShaharAriel** [comment]
Look at my link above.
